---
# For development purpose only
version: "3.8"

services:
  postgres-server:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-${ZABBIX_VERSION:-6.4}-latest
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_CACHEUPDATEFREQUENCY: 1
    depends_on:
      - postgres-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-${ZABBIX_VERSION:-6.4}-latest
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - postgres-server
      - zabbix-server

volumes:
  postgres_data: {}
